# DEPRECATED: The directory that holds any subsequent files mentioned.
# data_directory = './data/'
# TOML file defining the data backends for the entity unmarshaller services 
dbio_defs = './data/dbio.conf'
# The version number of the latest client release.
version = 204
# TCP/IP port number to listen for incoming connections on.
port = 43594
# Maximum number of players that this server can support.
max_players = 2048
# The TOML file containing incoming packet definitions.
packet_handler_table = './data/packets.toml'

[crypto]
# Length of hash output
hash_length = 32
# How many passes to do over the memory
hash_complexity = 15
# How much memory to use, in MiB
hash_memory = 8
# Salt to make hash output unique
hash_salt = 'rscgo./GOLANG!RULES/.1994'
